* Formato de número para texto ;
PROC FORMAT;
	VALUE estados_
		low - 09  = "Grande SP"
		10 - 19   = "Interior SP"
		19 <-< 29 = "Rio de Janeiro"
		30 - 39   = "Minas Gerais"
		80 - high = "Região sul"
		OTHER     = "Demais estados";
RUN;


DATA ALURA.CADASTRO_CLIENTE_V3;
	SET ALURA.cadastro_cliente_v2;
	
/* 	ESTADO = put(input(substr(cep,1,2),best.),estados_.); */
	
	IDADE = INTCK('YEAR', INPUT(NASCIMENTO, YYMMDD10.), MDY(12, 01, 2017), 'C');
	
RUN;

PROC FREQ 
	DATA=ALURA.CADASTRO_CLIENTE_V3;
	TABLE ESTADO IDADE;
RUN;

TITLE "QUANTIDADE DE CLIENTES POR ESTADO";

PROC SGPLOT
	DATA=ALURA.cadastro_cliente_v3;
	VBAR ESTADO / FILLATTRS=(COLOR=GREEN);
	YAXIS LABEL="NÚMERO DE CLIENTES"
		VALUES=(0 TO 35 BY 5) GRID 
		MINOR MINORCOUNT=4;
/* 	TITLE "QUANTIDADE DE CLIENTES POR ESTADO"; */
RUN;
TITLE;

PROC SGPLOT
	DATA=alura.CADASTRO_CLIENTE_V3;
	HISTOGRAM IDADE / FILLATTRS=(COLOR=GREEN);
	YAXIS GRID MINOR MINORCOUNT=9 LABEL="NÚMERO DE CLIENTES";
	XAXIS GRID MINOR MINORCOUNT=9 LABEL="NÚMERO DE CLIENTES";
	
RUN;

PROC UNIVARIATE
	DATA=ALURA.CADASTRO_CLIENTE_V3;
	VAR IDADE;
	HISTOGRAM;
RUN;
